### ISSUE TITLE
TLS private key compromised

### ISSUE THREAD

**Issue by maikthulhu** [incidrthreat/goshorten#6] opened 2020-07-17 21:18 UTC
https://github.com/incidrthreat/goshorten/blob/f840e8f29975ea99fa8c1aa5c4bccdc12570c8b7/backend/server.key#L1

Shipping pre-generated keypairs may compromise users who don't wish to (or care to) generate their own SSL certificates. Recommend pulling this ASAP. Once instructions/script to help generate and import certs is available publish that. Until then just put config placeholders for where people can reference the required files.

**Comment by incidrthreat** [comment] 2020-07-17 22:12
It was intended to be boilerplate certs, but knowing infosec users and potentially users of 3rd party apps such as this, the extra step of generating their own certs will probably not happen or get forgotten.  I've removed them and will work on either a script that will gen the certs on startup or develop a wiki to walk users through the steps prior to building.  Thanks Maik!

**Comment by incidrthreat** [comment] 2020-07-19 17:31
I might remove the TLS part of this completely since grpc communication is internal to a docker network and not exposed to anything outside docker.  Thoughts @maikthulhu?

**Comment by incidrthreat** [comment] 2020-07-25 06:59
Excellent discussion in DMs.  Added bash script to generate TLS certificates.  Closing issue.

**Closed as completed by incidrthreat** 2020-07-25 06:59 UTC
